delete from public.quiz_words where lesson = 18;

insert into public.quiz_words (lesson, word_no, correct_answer, part_of_speech, meaning, korean) values
(18, 1, 'environment', 'n.', 'the conditions that you live or work in and the way that they influence how you feel or how effectively you can work', '주위'),
(18, 2, 'freeze', 'v.', 'to lower something''s temperature below 0°C, causing it to become cold and often hard', '얼다'),
(18, 3, 'guide', 'n.', 'a person whose job is showing a place or a particular route to visitors', '안내자'),
(18, 4, 'hike', 'n.', 'a long walk, especially in the countryside', '도보여행'),
(18, 5, 'journey', 'n.', 'the act of travelling from one place to another, especially in a vehicle', '여행'),
(18, 6, 'kick', 'v.', 'to hit someone or something with the foot, or to move the feet and legs suddenly and violently', '차다'),
(18, 7, 'lake', 'n.', 'a large area of water surrounded by land and not connected to the sea except by rivers or streams', '호수'),
(18, 8, 'natural', 'adj.', 'as found in nature and not involving anything made or done by people', '자연스러운'),
(18, 9, 'path', 'n.', 'a route or track between one place and another, or the direction in which something is moving', '길'),
(18, 10, 'seed', 'n.', 'a small, round, or oval object produced by a plant and from which, when it is planted, a new plant can grow', '씨앗'),
(18, 11, 'basket', 'n.', 'a light container, often with a handle, that is made of thin strips of wood, metal, or plastic twisted together', '바구니'),
(18, 12, 'butter', 'n.', 'a pale yellow solid food containing a lot of fat that is made from cream and is spread on bread or used in cooking', '버터'),
(18, 13, 'cart', 'n.', 'a vehicle with either two or four wheels, pulled by a horse and used for carrying goods', '수레'),
(18, 14, 'coin', 'n.', 'a small, round piece of metal, usually silver or copper coloured, that is used as money', '동전'),
(18, 15, 'expression', 'n.', 'the act of saying what you think or showing how you feel using words or actions', '표현'),
(18, 16, 'math', 'n.', 'the study of numbers, shapes, and space using reason and usually a special system of symbols and rules for organizing them', '수학'),
(18, 17, 'museum', 'n.', 'a building where objects of historical, scientific, or artistic interest are kept', '박물관'),
(18, 18, 'tour', 'v.', 'a visit to a place or area, especially one during which you look around the place or area and learn about it', '관광하다'),
(18, 19, 'welcome', 'v.', 'to be pleased about and encourage or support something', '환영합니다'),
(18, 20, 'wrap', 'v.', 'to cover or surround something with paper, cloth, or other material', '포장하다'),
(18, 21, 'beans', 'n.', 'a seed, or the pod containing seeds, of various climbing plants, eaten as a vegetable', '콩류'),
(18, 22, 'carrot', 'n.', 'a long pointed orange root eaten as a vegetable', '당근'),
(18, 23, 'eggplant', 'n.', 'an oval, purple vegetable that is white inside and is usually eaten cooked', '가지'),
(18, 24, 'garlic', 'n.', 'a plant of the onion family that has a strong taste and smell and is used in cooking to add flavour', '마늘'),
(18, 25, 'lettuce', 'n.', 'a plant with large, green leaves, eaten uncooked in salad', '상추'),
(18, 26, 'peas', 'n.', 'a round, green seed, several of which grow in a pod, eaten as a vegetable', '완두류'),
(18, 27, 'potato', 'n.', 'a round vegetable that grows underground and has white flesh with light brown, red, or pink skin, or the plant on which these grow', '감자'),
(18, 28, 'radish', 'n.', 'a small vegetable, usually red or white and round or shaped like a finger, that grows underground and is usually eaten uncooked in salads', '무'),
(18, 29, 'spinach', 'n.', 'a vegetable with wide, dark green leaves that are eaten cooked or uncooked', '시금치'),
(18, 30, 'tomato', 'n.', 'a round, red fruit with a lot of seeds, eaten cooked or uncooked as a vegetable, for example in salads or sauces', '토마토'),
(18, 31, 'archery', 'n.', 'the art or sport of shooting arrows', '궁도'),
(18, 32, 'baseball', 'n.', 'a game played by two teams of 9 players, in which a player hits a ball with a bat and tries to run around four bases on a large field before the other team returns the ball', '야구'),
(18, 33, 'basketball', 'n.', 'a game played by two teams of 5 players who score points by throwing a large ball through an open net hanging from a metal ring', '농구'),
(18, 34, 'bowling', 'n.', 'a game played inside, in which you roll a heavy ball down a track to try to knock down a group of pins', '볼링'),
(18, 35, 'boxing', 'n.', 'a sport in which two competitors fight by hitting each other with their hands', '권투'),
(18, 36, 'fencing', 'n.', 'the sport of fighting with long, thin swords', '펜싱'),
(18, 37, 'golf', 'n.', 'a game played outside on grass in which each player tries to hit a small ball into a series of nine or 18 small holes, using a long, thin stick', '골프'),
(18, 38, 'lacrosse', 'n.', 'a game played by two teams in which the players each use a long stick with a net at the end to catch, carry, and throw a small ball, and try to get the ball in the other team''s goal', '라크로스'),
(18, 39, 'surfing', 'n.', 'the sport of riding on a wave on a special board', '서핑'),
(18, 40, 'tennis', 'n.', 'a game played between two or four people on a special playing area that involves hitting a small ball across a central net using a racket', '테니스'),
(18, 41, 'cheer', 'v.', 'to give a loud shout of approval or encouragement', '환호하다'),
(18, 42, 'coach', 'n.', 'someone whose job is to teach people to improve at a sport, skill, or school subject', '코치'),
(18, 43, 'court', 'n.', 'a place where trials and other legal cases happen', '경기장'),
(18, 44, 'crowd', 'n.', 'a large group of people who have come together', '군중'),
(18, 45, 'goal', 'n.', 'a point scored in some sports, such as football and hockey, when a player gets the ball into this area', '골'),
(18, 46, 'score', 'n.', 'the number of points, goals, etc. achieved in a game or competition', '점수'),
(18, 47, 'skate', 'v.', 'to move, or make a particular movement on a surface, using skates', '스케이트를 타다'),
(18, 48, 'spin', 'v.', 'to turn around and around, especially fast', '회전하다'),
(18, 49, 'toe', 'n.', 'any of the five separate parts at the end of the foot', '발가락'),
(18, 50, 'upset', 'adj.', 'worried, unhappy, or angry', '속상한'),
(18, 51, 'bar', 'n.', 'a piece of something which is roughly rectangular', '바'),
(18, 52, 'bite', 'v.', 'to use your teeth to cut into something or someone', '물다'),
(18, 53, 'contain', 'v.', 'to have something inside or include something as a part', '포함하다'),
(18, 54, 'dialog', 'n.', 'conversation that is written for a book, play, or film', '대화'),
(18, 55, 'imagine', 'v.', 'to form or have a mental picture or idea of something', '상상하다'),
(18, 56, 'lonely', 'adj.', 'unhappy because you are not with other people', '외로운'),
(18, 57, 'monster', 'n.', 'any imaginary frightening creature, especially one that is large and strange', '괴물'),
(18, 58, 'popular', 'adj.', 'liked, enjoyed, or supported by many people', '대중적인'),
(18, 59, 'soap', 'n.', 'a substance used for washing the body or other things', '비누'),
(18, 60, 'witch', 'n.', 'a woman who is believed to have magical powers and who uses them to harm or help other people', '마녀'),
(18, 61, 'dive', 'v.', 'to jump into water, especially with your head and arms going in first, or to move down under the water', '다이빙하다'),
(18, 62, 'excellent', 'adj.', 'extremely good', '훌륭한'),
(18, 63, 'holiday', 'n.', 'a time when someone does not go to work or school but is free to do what they want, such as travel or relax', '휴가'),
(18, 64, 'lovely', 'adj.', 'pleasant or enjoyable', '멋진'),
(18, 65, 'opinion', 'n.', 'a thought or belief about something or someone', '의견'),
(18, 66, 'pack', 'v.', 'to put something into a bag, box, etc.', '싸다'),
(18, 67, 'perform', 'v.', 'to do an action or piece of work', '공연하다'),
(18, 68, 'stamp', 'n.', 'a small piece of paper with a picture that is stuck onto a letter before it is posted', '우표'),
(18, 69, 'sweater', 'n.', 'a piece of clothing, typically with long sleeves and made from wool, that is worn on the upper part of the body', '스웨터'),
(18, 70, 'sweatshirt', 'n.', 'a piece of informal clothing with long sleeves, usually made of thick cotton, worn on the upper part of the body', '추리닝 상의'),
(18, 71, 'candy', 'n.', 'a sweet food made from sugar or chocolate, or a piece of this', '캔디'),
(18, 72, 'clue', 'n.', 'a sign or some information that helps you to find the answer to a problem, question, or mystery', '단서'),
(18, 73, 'exam', 'n.', 'a test of a student''s knowledge or skill in a particular subject', '시험'),
(18, 74, 'flat', 'adj.', 'level and smooth, with no curved, high, or hollow parts', '평평한'),
(18, 75, 'fry', 'v.', 'to cook food in hot oil or fat', '기름에 튀기다'),
(18, 76, 'information', 'n.', 'facts about a situation, person, event, etc.', '정보'),
(18, 77, 'pair', 'n.', 'two things of the same appearance and size that are intended to be used together', '켤레'),
(18, 78, 'picnic', 'n.', 'an occasion when you have an informal meal of sandwiches, etc. outside, or the food itself', '소풍'),
(18, 79, 'prepare', 'v.', 'to make or get something or someone ready for something that will happen in the future', '준비하다'),
(18, 80, 'quiz', 'n.', 'a game or competition in which you answer questions', '퀴즈');
