delete from public.quiz_words where lesson = 16;

insert into public.quiz_words (lesson, word_no, correct_answer, part_of_speech, meaning, korean) values
(16, 1, 'blind', 'adj.', 'unable to see', '눈먼'),
(16, 2, 'club', 'n.', 'an organization of people with a common purpose or interest, who meet regularly and take part in shared activities', '클럽'),
(16, 3, 'fair', 'adj.', 'treating someone in a way that is right or reasonable', '공정한'),
(16, 4, 'grade', 'n.', 'a number or letter that shows how good someone''s work or performance is', '성적'),
(16, 5, 'lesson', 'n.', 'a period of time in which a person is taught about a subject or how to do something', '수업'),
(16, 6, 'level', 'n.', 'someone''s ability compared to other people', '수준'),
(16, 7, 'master', 'n.', 'a male school teacher', '교사'),
(16, 8, 'recently', 'adv.', 'not long ago, or at a time that started not long ago', '최근에'),
(16, 9, 'review', 'n.', 'the act of considering something again in order to make changes to it, give an opinion of it or study it', '검토'),
(16, 10, 'sauce', 'n.', 'a thick liquid eaten with food to add flavour', '소스'),
(16, 11, 'bark', 'v.', 'to make loud, short sounds', '짖다'),
(16, 12, 'eyebrow', 'n.', 'the thin line of hair that is above each eye', '눈썹'),
(16, 13, 'eyelid', 'n.', 'the piece of skin that covers the eye when you close it', '눈꺼풀'),
(16, 14, 'heel', 'n.', 'the back part of your foot', '뒤꿈치'),
(16, 15, 'hobby', 'n.', 'an activity that you like and often do when you are not working', '취미'),
(16, 16, 'location', 'n.', 'a place or position', '장소'),
(16, 17, 'pattern', 'n.', 'a design of lines, shapes, colours, etc.', '무늬'),
(16, 18, 'polite', 'adj.', 'behaving in a way that is not rude and shows that you think about other people', '공손한'),
(16, 19, 'response', 'n.', 'an answer or reaction to something that has been said or done', '응답'),
(16, 20, 'topic', 'n.', 'a subject that you talk or write about', '화제'),
(16, 21, 'borrow', 'v.', 'to use something that belongs to someone else and then return it to them', '빌리다'),
(16, 22, 'choice', 'n.', 'the possibility of choosing between two or more things', '선택'),
(16, 23, 'confuse', 'v.', 'to stop someone from understanding something', '혼동하다'),
(16, 24, 'either', 'conj.', 'used when you are giving a choice of two or more things', '(둘중의)하나'),
(16, 25, 'float', 'v.', 'to stay on the surface of a liquid and not go under', '뜨다'),
(16, 26, 'flood', 'v.', 'to become covered with water', '범람하다'),
(16, 27, 'focus', 'v.', 'to direct attention toward something or someone', '집중하다'),
(16, 28, 'nervous', 'adj.', 'worried and anxious', '불안해 하는'),
(16, 29, 'similar', 'adj.', 'looking or being almost, but not exactly, the same', '비슷한'),
(16, 30, 'traditional', 'adj.', 'following or belonging to the customs or ways of behaving that have continued in a group of people or society for a long time', '전통의'),
(16, 31, 'aloud', 'adv.', 'in a voice loud enough to be heard', '큰소리로'),
(16, 32, 'discuss', 'v.', 'to talk about a subject with someone and tell each other your ideas or opinions', '토론하다'),
(16, 33, 'email', 'n.', 'the system for using computers to send messages over the internet', '이메일'),
(16, 34, 'gather', 'v.', 'to collect several things, often from different places or people', '모으다'),
(16, 35, 'invite', 'v.', 'to ask or request someone to go to an event', '초대하다'),
(16, 36, 'pie', 'n.', 'a type of food made with meat, vegetables, or fruit covered in pastry and baked', '파이'),
(16, 37, 'proud', 'adj.', 'feeling pleasure and satisfaction because you or people connected with you have done or got something good', '자부심이 있는'),
(16, 38, 'repeat', 'v.', 'to say or tell people something more than once', '반복하다'),
(16, 39, 'traffic', 'n.', 'the number of vehicles moving along roads, or the amount of aircraft, trains, or ships moving along a route', '교통'),
(16, 40, 'trick', 'n.', 'an action that is intended to deceive, either as a way of cheating someone, or as a joke or form of entertainment', '묘기'),
(16, 41, 'cell', 'n.', 'the smallest basic unit of a plant or animal', '세포'),
(16, 42, 'compare', 'v.', 'to examine or look for the difference between two or more things', '비교하다'),
(16, 43, 'cough', 'v.', 'to force air out of your lungs through your throat with a short, loud sound', '기침하다'),
(16, 44, 'figure out', 'phr.', 'to understand or solve something', '생각해 내다'),
(16, 45, 'flag', 'n.', 'a piece of cloth, usually rectangular and attached to a pole at one edge, that has a pattern that shows it represents a country or a group', '깃발'),
(16, 46, 'luck', 'n.', 'the force that causes things, especially good things, to happen to you by chance and not as a result of your own efforts or abilities', '행운'),
(16, 47, 'medicine', 'n.', 'treatment for illness or injury, or the study of this', '약'),
(16, 48, 'member', 'n.', 'a person, animal, or thing that is part of a group', '멤버'),
(16, 49, 'object', 'n.', 'a thing that you can see or touch but that is not usually a living animal, plant, or person', '물건'),
(16, 50, 'sore', 'adj.', 'painful and uncomfortable because of injury, infection, or too much use', '아픈'),
(16, 51, 'bell', 'n.', 'an electrical device that makes a ringing sound when you press a button', '종'),
(16, 52, 'blank', 'adj.', 'empty or clear, or containing no information or mark', '텅빈'),
(16, 53, 'develop', 'v.', 'to (cause something to) grow or change into a more advanced, larger, or stronger form', '발전하다'),
(16, 54, 'directions', 'n.', 'the position towards which someone or something moves or faces', '길안내'),
(16, 55, 'illness', 'n.', 'a disease of the body or mind', '병'),
(16, 56, 'passage', 'n.', 'a usually long and narrow part of a building with rooms on one or both sides, or a covered path that connects places', '통로'),
(16, 57, 'poison', 'n.', 'a substance that can make people or animals ill or kill them if they eat or drink it', '독극물'),
(16, 58, 'pole', 'n.', 'a long, thin stick of wood or metal, often used standing straight up in the ground to support things', '기둥'),
(16, 59, 'possible', 'adj.', 'able to be done or achieved, or able to exist', '가능한'),
(16, 60, 'summarize', 'v.', 'to express the most important facts or ideas about something or someone in a short and clear form', '요약하다'),
(16, 61, 'alligator', 'n.', 'a large reptile with a hard skin that lives in and near rivers and lakes in the hot, wet parts of America and China', '앨리게이터'),
(16, 62, 'chameleon', 'n.', 'a lizard that changes skin colour to match what surrounds it so that it cannot be seen', '카멜레온'),
(16, 63, 'cobra', 'n.', 'a poisonous snake from Africa and southern Asia', '코브라'),
(16, 64, 'crocodile', 'n.', 'a large reptile with a hard skin that lives in and near rivers and lakes in hot, wet parts of the world', '악어'),
(16, 65, 'dinosaur', 'n.', 'a type of reptile that became extinct about 65,000,000 years ago', '공룡'),
(16, 66, 'gecko', 'n.', 'a small lizard with wide feet, found especially in warm countries', '도마뱀붙이'),
(16, 67, 'iguana', 'n.', 'a large greyish-green lizard of tropical America', '이구아나'),
(16, 68, 'lizard', 'n.', 'a small reptile that has a long body, four short legs, a long tail, and thick skin', '도마뱀'),
(16, 69, 'rattlesnake', 'n.', 'a poisonous snake found in southern parts of the US that, when annoyed, produces a loud noise by shaking its tail', '방울뱀'),
(16, 70, 'tortoise', 'n.', 'an animal with a thick, hard shell that it can move its head and legs into for protection', '거북'),
(16, 71, 'angelfish', 'n.', 'any of a number of laterally compressed deep-bodied fish with extended dorsal and anal fins, typically brightly colored or boldly striped', '전자리 상어'),
(16, 72, 'catfish', 'n.', 'a fish with a flat head and long hairs around its mouth that lives in rivers or lakes', '메기'),
(16, 73, 'clownfish', 'n.', 'a small fish that is usually red, orange, or yellow with white stripes, and lives in warm or tropical seas', '흰동가리'),
(16, 74, 'cod', 'n.', 'a large sea fish that can be eaten', '대구'),
(16, 75, 'parrot fish', 'n.', 'any of a number of brightly colored marine fish with a parrotlike beak, which they use to scrape food from coral and other hard surfaces', '비늘돔'),
(16, 76, 'salmon', 'n.', 'a medium-sized silver-coloured fish that lives in the sea or rivers and swims up rivers to produce its eggs', '연어'),
(16, 77, 'sardine', 'n.', 'a small sea fish that can be eaten', '정어리'),
(16, 78, 'swordfish', 'n.', 'a large, long fish that is often eaten as food, with a very long pointed part like a beak at the front of its head', '황새치'),
(16, 79, 'trout', 'n.', 'a fish that lives in rivers and lakes, or lives in the sea but returns to rivers to produce its eggs', '송어'),
(16, 80, 'tuna', 'n.', 'a large fish that lives in warm seas', '참치');
