delete from public.quiz_words where lesson = 20;

insert into public.quiz_words (lesson, word_no, correct_answer, part_of_speech, meaning, korean) values
(20, 1, 'bottle', 'n.', 'a container for liquids, usually made of glass or plastic, with a narrow neck', '병'),
(20, 2, 'bowl', 'n.', 'a round container that is open at the top and is deep enough to hold fruit, sugar, etc.', '(그릇)사발'),
(20, 3, 'cheese', 'n.', 'a food made from milk, that can be either firm or soft and is usually yellow or white in colour', '치즈'),
(20, 4, 'dishes', 'n.', 'a container, flatter than a bowl and sometimes with a lid, from which food can be served or which can be used for cooking', '접시'),
(20, 5, 'fork', 'n.', 'a small object with three or four points and a handle, that you use to pick up food and eat with', '포크'),
(20, 6, 'huge', 'adj.', 'extremely large in size or amount', '거대한'),
(20, 7, 'ice cream', 'n.', 'a very cold, sweet food made from frozen milk or cream, sugar, and a flavour', '아이스크림'),
(20, 8, 'knife', 'n.', 'a tool, usually with a metal blade and a handle, used for cutting and spreading food or other substances, or as a weapon', '칼'),
(20, 9, 'meal', 'n.', 'an occasion when food is eaten, or the food that is eaten on such an occasion', '식사'),
(20, 10, 'spoon', 'n.', 'an object consisting of a round, hollow part and a handle, used for mixing, serving, and eating food', '숟가락'),
(20, 11, 'alarm', 'n.', 'a warning of danger, usually a loud noise or flashing light', '경보'),
(20, 12, 'asleep', 'adj.', 'sleeping or not awake', '자고 있는'),
(20, 13, 'cloud', 'n.', 'a grey or white mass in the sky, made up of very small floating drops of water', '구름'),
(20, 14, 'mad', 'adj.', 'very angry or annoyed', '화난'),
(20, 15, 'nurse', 'n.', 'a person whose job is to care for people who are ill or injured, especially in a hospital', '간호사'),
(20, 16, 'pool', 'n.', 'a small area of usually still water', '수영장'),
(20, 17, 'rainbow', 'n.', 'an arch of different colours seen in the sky when rain is falling and the sun is shining', '무지개'),
(20, 18, 'sand', 'n.', 'a substance that consists of very small grains of rock, found on beaches and in deserts', '모래'),
(20, 19, 'storm', 'n.', 'an extreme weather condition with very strong wind, heavy rain, and often thunder and lightning', '폭풍'),
(20, 20, 'wake up', 'phr.', 'become awake and conscious after sleeping', '정신을 차리다'),
(20, 21, 'brush', 'n.', 'an object with short pieces of stiff hair, plastic, or wire attached to a base or handle, used for cleaning, arranging your hair, or painting', '솔'),
(20, 22, 'daughter', 'n.', 'your female child', '딸'),
(20, 23, 'neighbor', 'n.', 'someone who lives near you', '이웃'),
(20, 24, 'ocean', 'n.', 'a very large area of sea', '해양'),
(20, 25, 'photograph', 'n.', 'a picture produced using a camera', '사진'),
(20, 26, 'pocket', 'n.', 'a small bag for carrying things in, made of cloth and sewn into the inside or onto the outside of a piece of clothing', '호주머니'),
(20, 27, 'smart', 'adj.', 'intelligent, or able to think quickly or intelligently in difficult situations', '영리한'),
(20, 28, 'son', 'n.', 'your male child', '아들'),
(20, 29, 'square', 'n.', 'a flat shape with four sides of equal length and four angles of 90 degrees', '정사각형'),
(20, 30, 'thumb', 'n.', 'the short, thick finger on the side of your hand that makes it possible to hold and pick things up easily', '엄지손가락'),
(20, 31, 'amazing', 'adj.', 'extremely surprising', '놀라운'),
(20, 32, 'bug', 'n.', 'a very small insect', '벌레'),
(20, 33, 'can', 'n.', 'a closed metal container, especially cylinder-shaped, in which some types of drink and food are sold', '깡통'),
(20, 34, 'chip', 'n.', 'a small piece that has been broken off a larger object', '칩'),
(20, 35, 'drum', 'n.', 'a musical instrument, played by hitting with the hand or a stick', '드럼'),
(20, 36, 'soccer', 'n.', 'a game played between two teams of eleven people, where each team tries to win by kicking a ball into the other team''s goal', '축구'),
(20, 37, 'theater', 'n.', 'a building, room, or outside structure with rows of seats, from which people can watch a performance or other activity', '극장'),
(20, 38, 'ticket', 'n.', 'a small piece of paper or card given to someone, usually to show that they have paid for an event, journey, or activity', '티켓'),
(20, 39, 'tiny', 'adj.', 'extremely small', '아주 작은'),
(20, 40, 'wing', 'n.', 'the flat part of the body that a bird, insect, or bat uses for flying', '날개'),
(20, 41, 'bath', 'n.', 'a long plastic, metal, or ceramic container that is filled with water so that you can sit or lie in it to wash your whole body', '목욕'),
(20, 42, 'born', 'v.', 'to come out of a mother''s body, and start to exist', '태어나다'),
(20, 43, 'chase', 'v.', 'to hurry after someone or something in order to catch him, her, or it', '뒤쫓다'),
(20, 44, 'date', 'n.', 'a numbered day in a month, often given with a combination of the name of the day, the month, and the year', '날짜'),
(20, 45, 'feather', 'n.', 'one of the many soft, light things that cover a bird''s body, consisting of a long, thin, central part with material like hairs along each side', '깃털'),
(20, 46, 'gift', 'n.', 'a present or something that is given', '선물'),
(20, 47, 'lock', 'n.', 'a device that prevents something such as a door from being opened and can only be opened with a key', '자물쇠'),
(20, 48, 'magazine', 'n.', 'a type of thin book with large pages and a paper cover that contains articles and photographs and is published every week or month', '잡지'),
(20, 49, 'skin', 'n.', 'the natural outer layer that covers a person, animal, fruit, etc.', '피부'),
(20, 50, 'yard', 'n.', 'a unit of measurement equal to three feet or approximately 91.4 centimetres', '마당'),
(20, 51, 'adult', 'n.', 'a person or an animal that has grown to full size and strength', '성인'),
(20, 52, 'giant', 'adj.', 'extremely large', '거대한'),
(20, 53, 'lazy', 'adj.', 'not willing to work or use any effort', '게으른'),
(20, 54, 'menu', 'n.', 'a list of the food that you can eat in a restaurant', '메뉴'),
(20, 55, 'planet', 'n.', 'an extremely large, round mass of rock and metal', '행성'),
(20, 56, 'rice', 'n.', 'the small seeds of a particular type of grass, cooked, and eaten as food', '밥'),
(20, 57, 'salad', 'n.', 'a mixture of uncooked vegetables, usually including lettuce, eaten either as a separate dish or with other food', '샐러드'),
(20, 58, 'salt', 'n.', 'a common white substance found in sea water and in the ground, used especially to add flavour to food or to preserve it', '소금'),
(20, 59, 'serve', 'v.', 'to provide food or drinks', '제공하다'),
(20, 60, 'soup', 'n.', 'a usually hot, liquid food made from vegetables, meat, or fish', '수프'),
(20, 61, 'brave', 'adj.', 'showing no fear of dangerous or difficult things', '용감한'),
(20, 62, 'ghost', 'n.', 'the spirit of a dead person', '유령'),
(20, 63, 'hero', 'n.', 'a person who is admired for having done something very brave or having achieved something great', '영웅'),
(20, 64, 'low', 'adj.', 'below the usual level', '줄어든'),
(20, 65, 'scary', 'adj.', 'frightening', '무서운'),
(20, 66, 'tail', 'n.', 'a part of an animal''s body, sticking out from the base of the back, or something similar in shape or position', '꼬리'),
(20, 67, 'thick', 'adj.', 'having a large distance between two sides', '두꺼운'),
(20, 68, 'thin', 'adj.', 'having a small distance between two opposite sides', '얇은'),
(20, 69, 'tip', 'n.', 'the usually pointed end of something, especially something that is long and thin', '끝'),
(20, 70, 'wet', 'adj.', 'covered in water or another liquid', '젖은'),
(20, 71, 'against', 'prep.', 'next to and touching or being supported by something', '~에 기대어'),
(20, 72, 'bone', 'n.', 'any of the hard parts inside a human or animal that make up its frame', '뼈'),
(20, 73, 'firefighter', 'n.', 'a person whose job is to stop fires from burning', '소방수'),
(20, 74, 'item', 'n.', 'something that is part of a list or group of things', '항목'),
(20, 75, 'library', 'n.', 'a building, room, or organization that has a collection, especially of books, for people to read or borrow, usually without payment', '도서관'),
(20, 76, 'pan', 'n.', 'a metal container that is round and often has a long handle and a lid, used for cooking things on top of a cooker', '납작한 냄비'),
(20, 77, 'pot', 'n.', 'any of various types of container, usually round, especially one used for cooking food', '냄비'),
(20, 78, 'string', 'n.', 'strong, thin rope made by twisting very thin threads together, used for fastening and tying things', '실'),
(20, 79, 'sugar', 'n.', 'a sweet substance especially from the plants sugar cane and sugar beet, used to make food and drinks sweet', '설탕'),
(20, 80, 'wild', 'adj.', 'used to refer to plants or animals that live or grow independently of people', '야생의');
