delete from public.quiz_words where lesson = 17;

insert into public.quiz_words (lesson, word_no, correct_answer, part_of_speech, meaning, korean) values
(17, 1, 'beside', 'prep.', 'at the side of, next to', '옆에'),
(17, 2, 'block', 'n.', 'the distance along a street from where one road crosses it to the place where the next road crosses it', '블록'),
(17, 3, 'center', 'n.', 'the middle point or part', '중심'),
(17, 4, 'challenge', 'n.', 'something that needs great mental or physical effort in order to be done successfully and therefore tests a person''s ability', '도전'),
(17, 5, 'decorate', 'v.', 'to add something to an object or place, especially in order to make it more attractive', '장식하다'),
(17, 6, 'melt', 'v.', 'to turn from something solid into something soft or liquid, or to cause something to do this', '녹다'),
(17, 7, 'olive', 'n.', 'a small bitter green or black fruit that is eaten or used to produce oil, or a Mediterranean tree on which this fruit grows', '올리브'),
(17, 8, 'probably', 'adv.', 'used to mean that something is very likely', '아마도'),
(17, 9, 'record', 'v.', 'to store sounds or moving pictures using electronic equipment so that they can be heard or seen later', '기록하다'),
(17, 10, 'volcano', 'n.', 'a mountain with a large, circular hole at the top through which lava, gases, steam, and dust are or have been forced out', '화산'),
(17, 11, 'bow', 'v.', 'to bend your head or body forward, especially as a way of showing someone respect', '머리를 숙이다'),
(17, 12, 'enter', 'v.', 'to come or go into a particular place', '들어가다'),
(17, 13, 'hip', 'n.', 'the area below the waist and above the legs at either side of the body, or the joint that connects the leg to the upper part of the body', '둔부(골반부위)'),
(17, 14, 'joke', 'n.', 'something, such as a funny story or trick, that is said or done in order to make people laugh', '농담'),
(17, 15, 'nephew', 'n.', 'a son of your sister or brother, or a son of the sister or brother of your husband or wife', '조카'),
(17, 16, 'niece', 'n.', 'a daughter of your brother or sister, or a daughter of your husband''s or wife''s brother or sister', '조카딸'),
(17, 17, 'scientist', 'n.', 'an expert who studies or works in one of the sciences', '과학자'),
(17, 18, 'silly', 'adj.', 'showing little thought or judgment', '어리석은'),
(17, 19, 'throat', 'n.', 'the front of the neck, or the space inside the neck down which food and air can go', '목구멍'),
(17, 20, 'village', 'n.', 'a group of houses and other buildings that is smaller than a town, usually in the countryside', '마을'),
(17, 21, 'advice', 'n.', 'an opinion that someone offers you about what you should do or how you should act in a particular situation', '충고'),
(17, 22, 'comma', 'n.', 'the symbol, used in writing to separate parts of a sentence showing a slight pause', '쉼표'),
(17, 23, 'hug', 'v.', 'to hold someone close to your body with your arms, usually to show that you like, love, or value them', '포옹하다'),
(17, 24, 'invent', 'v.', 'to design and/or create something that has never been made before', '발명하다'),
(17, 25, 'kiss', 'v.', 'to touch with your lips, especially as a greeting, or to press your mouth onto another person''s mouth in a sexual way', '키스하다'),
(17, 26, 'palm', 'n.', 'the inside part of your hand from your wrist to the base of your fingers', '손바닥'),
(17, 27, 'president', 'n.', 'the person who has the highest political position in a country', '대통령'),
(17, 28, 'state', 'n.', 'a part of a large country with its own government, such as in Germany, Australia, or the US', '주'),
(17, 29, 'tower', 'n.', 'a tall, narrow structure, often square or circular, that either forms part of a building or stands alone', '타워'),
(17, 30, 'wedding', 'n.', 'a marriage ceremony and any celebrations such as a meal or a party that follow it', '혼례'),
(17, 31, 'blanket', 'n.', 'a flat cover made of wool or similar warm material, usually used on a bed', '담요'),
(17, 32, 'energy', 'n.', 'the power and ability to be physically and mentally active', '에너지'),
(17, 33, 'gate', 'n.', 'a part of a fence or outside wall that is fixed at one side and opens and closes like a door', '문'),
(17, 34, 'jaw', 'n.', 'the lower part of your face that moves when you open your mouth', '턱'),
(17, 35, 'notice', 'v.', 'to see or become conscious of something or someone', '주의하다'),
(17, 36, 'opposite', 'adj.', 'being in a position on the other side; facing', '반대편의'),
(17, 37, 'search', 'v.', 'to look somewhere carefully in order to find something', '수색'),
(17, 38, 'shell', 'n.', 'the hard outer covering of something, especially nuts, eggs, and some animals', '껍데기'),
(17, 39, 'swimsuit', 'n.', 'a piece of clothing that you wear for swimming', '수영복'),
(17, 40, 'ugly', 'adj.', 'unpleasant to look at; not attractive', '못생긴'),
(17, 41, 'bracelet', 'n.', 'a piece of jewellery that is worn around the wrist or arm', '팔찌'),
(17, 42, 'earrings', 'n.', 'a piece of jewellery, usually one of a pair, worn in a hole in the ear or fastened to the ear by a clip', '귀걸이'),
(17, 43, 'gloves', 'n.', 'a piece of clothing that is worn on the hand and wrist for warmth or protection, with separate parts for each finger', '장갑'),
(17, 44, 'cap', 'n.', 'a soft flat hat that has a curved part sticking out at the front, often worn as part of a uniform', '모자'),
(17, 45, 'necklace', 'n.', 'a piece of jewellery worn around the neck, such as a chain or a string of decorative stones, beads, etc.', '목걸이'),
(17, 46, 'purse', 'n.', 'a small container for money, usually used by a woman', '지갑'),
(17, 47, 'sunglasses', 'n.', 'dark glasses that you wear to protect your eyes from bright light from the sun', '선글라스'),
(17, 48, 'umbrella', 'n.', 'an object consisting of a long stick with a folding frame covered in cloth to protect yourself from the rain or hot sun', '우산'),
(17, 49, 'wallet', 'n.', 'a small folding case for carrying paper money, credit cards and other flat objects, that can be carried in a pocket and is used especially by men', '지갑'),
(17, 50, 'watch', 'n.', 'a small clock that you wear on your wrist', '손목시계'),
(17, 51, 'ax', 'n.', 'a tool consisting of a heavy iron or steel blade at the end of a long wooden handle, used for cutting wood', '도끼'),
(17, 52, 'drill', 'n.', 'a tool or machine that makes holes', '드릴'),
(17, 53, 'hammer', 'n.', 'a tool consisting of a piece of metal with a flat end that is fixed onto the end of a long, thin, usually wooden handle, used for hitting things', '망치'),
(17, 54, 'hose', 'n.', 'a long plastic or rubber pipe, used to direct water onto fires, gardens, etc.', '호스'),
(17, 55, 'nail', 'n.', 'a small, thin piece of metal with one pointed end and one flat end that you hit into something with a hammer', '못'),
(17, 56, 'rake', 'n.', 'a garden tool with a long handle and long, pointed metal parts sticking out in a row at the bottom', '갈퀴'),
(17, 57, 'saw', 'n.', 'a tool with a long or round blade with teeth along one edge, used for cutting hard materials such as wood or metal', '톱'),
(17, 58, 'screw', 'n.', 'a thin, pointed piece of metal used to join things together, especially pieces of wood', '나사'),
(17, 59, 'screwdriver', 'n.', 'a tool for turning screws, consisting of a handle joined to a metal rod shaped at one end to fit in the cut in the top of the screw', '드라이버'),
(17, 60, 'wrench', 'n.', 'a tool for holding and turning objects, especially one that can be made larger and smaller to hold different sized objects', '렌치'),
(17, 61, 'armpit', 'n.', 'the hollow place under your arm where your arm joins your body', '겨드랑이'),
(17, 62, 'brain', 'n.', 'the organ inside the head that controls thought, memory, feelings, and activity', '뇌'),
(17, 63, 'colon', 'n.', 'the lower and bigger half of the bowels in which water is removed from solid waste', '결장'),
(17, 64, 'connect', 'v.', 'to join or be joined with something else', '연결하다'),
(17, 65, 'hundred', 'n.', 'the number 100', '숫자 100'),
(17, 66, 'million', 'n.', 'the number 1,000,000', '백만'),
(17, 67, 'relax', 'v.', 'to become less active and more calm and happy, or to cause someone or a part of the body to become less stiff', '진정시키다'),
(17, 68, 'stomach', 'n.', 'an organ in the body where food is digested, or the soft front part of your body just below the chest', '위'),
(17, 69, 'thousand', 'n.', 'the number 1,000', '숫자 1000'),
(17, 70, 'waist', 'n.', 'the part of the body above and slightly narrower than the hips', '허리'),
(17, 71, 'army', 'n.', 'a particular country''s fighting force', '육군'),
(17, 72, 'belong', 'v.', 'to be in the right place or a suitable place', '속하다'),
(17, 73, 'cage', 'n.', 'a space surrounded on all sides by bars or wire, in which animals or birds are kept', '(작은)우리'),
(17, 74, 'common', 'adj.', 'the same in a lot of places or for a lot of people', '공통의'),
(17, 75, 'escape', 'v.', 'to get free from something, or to avoid something', '탈출하다'),
(17, 76, 'mail', 'n.', 'the letters, etc. that are sent to or from people, or the system for sending letters, etc. from place to place', '우편물'),
(17, 77, 'mix', 'v.', 'to combine different substances, so that the result cannot easily be separated into its parts', '섞다'),
(17, 78, 'post', 'v.', 'to stick or pin a notice on a wall in order to make it publicly known', '게시하다'),
(17, 79, 'shiny', 'adj.', 'bright because it reflects light', '반짝거리다'),
(17, 80, 'soldier', 'n.', 'a person who is in an army and wears its uniform, especially someone who fights when there is a war', '군인');
